# 595. Big Countries

# Write your MySQL query statement below
SELECT NAME, POPULATION, AREA
FROM WORLD
WHERE AREA >= 3000000 

UNION

SELECT NAME, POPULATION, AREA
FROM WORLD
WHERE POPULATION >= 25000000